"""Regenerates src/MindControl/Policy/RiftWalls.Cells.cs from the navgrid.

The source is the 2024 Summoner's Rift vision-pathing layer as exported by
FrankTheBoxMonster's LoL-NGRID-converter
(SR_2024/navgrids/Base/AIPath_SRX_3.VisionPathing.bmp), which is not checked
in; fetch it into data/navgrid/ (gitignored) first:

    curl -sSL -o data/navgrid/AIPath_SRX_3.VisionPathing.bmp \
      https://raw.githubusercontent.com/FrankTheBoxMonster/LoL-NGRID-converter/HEAD/SR_2024/navgrids/Base/AIPath_SRX_3.VisionPathing.bmp
    python etc/navgrid-walls.py

Needs Pillow.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data/navgrid/AIPath_SRX_3.VisionPathing.bmp"
TARGET = ROOT / "src/MindControl/Policy/RiftWalls.Cells.cs"

# Walls, structures (turrets, inhibitors, nexuses: standing or not, their
# footprint stays unwalkable), and the see-through walls on brush edges.
BLOCKED = {(64, 64, 64), (0, 210, 214), (0, 216, 111)}
# Not listed, so counted walkable: brush, and the few cells at each base's
# gates only one side can pass (blue's shades in blue's base, red's in red's),
# which a coached player's walk has no business near on the other side.


def runs(image, colours):
    width, height = image.size
    rows = []
    for row in range(height):
        found, column = [], 0
        while column < width:
            if image.getpixel((column, row)) in colours:
                first = column
                while column < width and image.getpixel((column, row)) in colours:
                    column += 1
                found += [first, column - 1]
            else:
                column += 1
        rows.append(found)
    return rows


def emit(name, rows):
    lines = [f"    private static int[][] {name} =>", "    ["]
    lines += [f"        [{', '.join(map(str, r))}]," for r in rows]
    lines.append("    ];")
    return lines


def main():
    image = Image.open(SOURCE).convert("RGB")
    assert image.size == (295, 296), image.size
    out = [
        "// <auto-generated> by etc/navgrid-walls.py from the vision-pathing layer; do not edit by hand. </auto-generated>",
        "namespace MindControl.Policy;",
        "",
        "public static partial class RiftWalls",
        "{",
        "    /// <summary>Per navgrid row, top (north) first: (first column, last column) of each run of cells no one can walk on.</summary>",
    ]
    out += emit("BlockedRuns", runs(image, BLOCKED))
    out.append("}")
    TARGET.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\r\n")


if __name__ == "__main__":
    main()
