"""Regenerates src/MindControl/Policy/RiftMap.Landmarks.cs from the game's map data.

The source is Summoner's Rift's base scene as CommunityDragon extracts it from
the live client (game/data/maps/mapgeometry/map11/base_srx.materials.bin.json),
which is not checked in; fetch it into data/cdragon/ (gitignored) first:

    curl -sSL -o data/cdragon/base_srx.materials.bin.json \
      https://raw.communitydragon.org/latest/game/data/maps/mapgeometry/map11/base_srx.materials.bin.json
    python etc/rift-landmarks.py

Every jungle camp and river objective is an object placed in the scene with a
NeutralCamp component, whose camp record carries its CampName ("Order
OwlBear") and whose transform's last row is where it stands: x, height, and
the map's north-south axis, which RiftMap calls y. The same scene places the
22 turrets, which RiftMap's turret spots match exactly.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data/cdragon/base_srx.materials.bin.json"
TARGET = ROOT / "src/MindControl/Policy/RiftMap.Landmarks.cs"

# The game's names for the camps are their old ones: Order is blue, Chaos is
# red, an owlbear is gromp, wraiths are raptors, small golems are krugs.
SIDES = {"Order": "MapSide.Blue", "Chaos": "MapSide.Red"}
CAMPS = {
    "Blue": "blue buff", "OwlBear": "gromp", "Wolves": "wolves",
    "Wraiths": "raptors", "Red": "red buff", "Small Golems": "krugs",
}
RIVER = {
    "Dragon": "dragon pit", "Baron": "baron pit",
    "Baron Crab": "top scuttle crab", "Dragon Crab": "bot scuttle crab",
}
# Spawn in the baron pit, which names the spot already.
SKIPPED = {"Horde", "SRU_RiftHerald"}


def placed_camps(scene):
    names = {key: value["CampName"] for key, value in scene.items()
             if isinstance(value, dict) and "CampName" in value}
    found = {}

    def walk(node):
        if isinstance(node, dict):
            if "NeutralCamp" in node and "transform" in node:
                camp = node["NeutralCamp"].get("{5a4ef4e7}")
                name = names.get(camp, camp)
                x, _, y, _ = node["transform"][3]
                assert name not in found, f"{name} placed twice"
                found[name] = (round(x), round(y))
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(scene)
    return found


def landmark(name, spot):
    x, y = spot
    if name in RIVER:
        return f'new("{RIVER[name]}", null, {x}, {y})'
    side, _, camp = name.partition(" ")
    assert side in SIDES and camp in CAMPS, f"unknown camp {name!r}"
    return f'new("{CAMPS[camp]}", {SIDES[side]}, {x}, {y})'


def main():
    found = placed_camps(json.loads(SOURCE.read_text(encoding="utf-8")))
    kept = {name: spot for name, spot in found.items() if name not in SKIPPED}
    assert len(kept) == 16, sorted(found)
    # Blue's camps, red's, then the river's, each in a fixed order.
    order = [f"{side} {camp}" for side in SIDES for camp in CAMPS] + list(RIVER)
    out = [
        "// <auto-generated> by etc/rift-landmarks.py from the game's map scene; do not edit by hand. </auto-generated>",
        "namespace MindControl.Policy;",
        "",
        "public sealed partial class RiftMap",
        "{",
        "    /// <summary>",
        "    /// The twelve jungle camps and four river spots, where the game's own",
        "    /// Summoner's Rift scene places them (CommunityDragon's extract of",
        "    /// base_srx.materials.bin): blue's camps, red's, then the river's.",
        "    /// </summary>",
        "    public static readonly Landmark[] Landmarks =",
        "    [",
    ]
    out += [f"        {landmark(name, kept[name])}," for name in order]
    out += ["    ];", "}"]
    TARGET.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\r\n")


if __name__ == "__main__":
    main()
