namespace MindControl.Policy;

/// <summary>
/// The ground on Summoner's Rift no one can walk on: the walls, the
/// see-through walls on brush edges, and the structures -- every turret,
/// inhibitor and nexus, whose footprint stays unwalkable after it falls.
/// Pure geometry, in the same game units as <see cref="RiftMap"/>: whether a
/// point can be walked on, and where along a line the nearest point that can
/// is. A click on ground that cannot be walked on walks the champion to the
/// nearest point that can and stops it there, so a walk's click is moved off
/// it (<see cref="ClearOfWalls"/>).
/// </summary>
/// <remarks>
/// From the same vision-pathing layer as <see cref="RiftBrush"/> (295 by 296
/// cells, 50 units each, cell (column c, row r) centred at x = 50c + 25,
/// y = 14810 - 50r), generated by <c>etc/navgrid-walls.py</c> into
/// <c>RiftWalls.Cells.cs</c>. The few cells at each base's gates that only
/// one side can pass count as walkable.
/// </remarks>
public static partial class RiftWalls
{
    private const int Columns = 295, Rows = 296;
    private const double Cell = 50;

    /// <summary>How finely <see cref="ClearOfWalls"/> walks a line: half a cell.</summary>
    private const double Stride = Cell / 2;

    private static readonly Lazy<bool[]> Blocked = new(() =>
    {
        var blocked = new bool[Columns * Rows];
        var runs = BlockedRuns;
        for (var row = 0; row < Rows; row++)
            for (var i = 0; i < runs[row].Length; i += 2)
                for (var column = runs[row][i]; column <= runs[row][i + 1]; column++)
                    blocked[row * Columns + column] = true;
        return blocked;
    });

    /// <summary>Whether a champion can stand at a point; off the map it cannot.</summary>
    public static bool Walkable(double x, double y)
    {
        var column = (int)Math.Floor(x / Cell);
        var row = (int)Math.Floor((14835 - y) / Cell);
        return column is >= 0 and < Columns && row is >= 0 and < Rows && !Blocked.Value[row * Columns + column];
    }

    /// <summary>
    /// How far from (<paramref name="x"/>, <paramref name="y"/>) along the
    /// unit direction (<paramref name="ux"/>, <paramref name="uy"/>), y
    /// north, a click meant to land <paramref name="units"/> away should land
    /// so it is on ground that can be walked on: <paramref name="units"/> when
    /// it already is, else the nearest distance that is, looking farther first
    /// (up to <paramref name="max"/>) so the game's own pathing takes the
    /// champion round what is in the way, then nearer. With
    /// <paramref name="nearerFirst"/> it looks nearer first: for a click on
    /// the place a walk ends at, which is better short of an obstacle than
    /// past it. <paramref name="units"/> unchanged when neither finds one.
    /// </summary>
    public static double ClearOfWalls(
        double x, double y, double ux, double uy, double units, double max, bool nearerFirst = false)
    {
        if (Walkable(x + ux * units, y + uy * units))
            return units;
        var farther = Search(units + Stride, Math.Max(max, units), Stride);
        var nearer = Search(units - Stride, Stride, -Stride);
        return (nearerFirst ? nearer ?? farther : farther ?? nearer) ?? units;

        double? Search(double from, double to, double stride)
        {
            for (var d = from; stride > 0 ? d <= to : d >= to; d += stride)
                if (Walkable(x + ux * d, y + uy * d))
                    return d;
            return null;
        }
    }
}
