// <auto-generated> by etc/rift-landmarks.py from the game's map scene; do not edit by hand. </auto-generated>
namespace MindControl.Policy;

public sealed partial class RiftMap
{
    /// <summary>
    /// The twelve jungle camps and four river spots, where the game's own
    /// Summoner's Rift scene places them (CommunityDragon's extract of
    /// base_srx.materials.bin): blue's camps, red's, then the river's.
    /// </summary>
    public static readonly Landmark[] Landmarks =
    [
        new("blue buff", MapSide.Blue, 3894, 7870),
        new("gromp", MapSide.Blue, 2178, 8430),
        new("wolves", MapSide.Blue, 3813, 6467),
        new("raptors", MapSide.Blue, 6969, 5422),
        new("red buff", MapSide.Blue, 7765, 4020),
        new("krugs", MapSide.Blue, 8390, 2675),
        new("blue buff", MapSide.Red, 11032, 6991),
        new("gromp", MapSide.Red, 12626, 6434),
        new("wolves", MapSide.Red, 10980, 8357),
        new("raptors", MapSide.Red, 7861, 9575),
        new("red buff", MapSide.Red, 7102, 10901),
        new("krugs", MapSide.Red, 6449, 12199),
        new("dragon pit", null, 9838, 4398),
        new("baron pit", null, 5007, 10471),
        new("top scuttle crab", null, 4400, 9600),
        new("bot scuttle crab", null, 10500, 5170),
    ];
}
